### ISSUE TITLE
Yii2-faker fixture Error

### ISSUE THREAD

**Issue by cherifGsoul** [yiisoft/yii2-app-basic#14]
Yii2 faker extension generate the folowing error 

```
Error: The template path "@tests/unit/templates/fixtures" does not exist"
```

the console.php configuration:

``` php
<?php

Yii::setAlias('@tests', dirname(__DIR__) . '/tests');

$params = require(__DIR__ . '/params.php');
$db = require(__DIR__ . '/db.php');

return [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'gii'],
    'controllerNamespace' => 'app\commands',
    'controllerMap' => [
    'fixture' => [
            'class' => 'yii\faker\FixtureController'
        ],
    ],
    'modules' => [
        'gii' => 'yii\gii\Module',
    ],
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,
    ],
    'params' => $params,
];
```

**Comment by samdark** [comment]
The error says it itself. You don't have templates at that path.

**Comment by cherifGsoul** [comment]
@samdark I use the default template path in the command controller, it should point to "@tests/codeception/unit/templates/fixtures" the codeception folder is missing, to fix this we can:
change the @"test" alias to 
```php
Yii::setAlias('@tests', dirname(__DIR__) . '/tests/codeception'); 
```
or configure the command controller templatePath param to:
```php
'templatePath' => '@tests/codeception/unit/templates/fixtures',
```

**Comment by YasserHassan** [comment]
There's a mismatch between the `fixtures` and `templates` locations suggested by the basic application template (@tests\codeception\unit\fixtures and @tests\codeception\unit\templates) and those mentioned in the documentation [here](http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html#organizing-fixture-classes-and-data-files). The existence of other `fixtures` and `templates` directly under the `codeception` folder makes it more confusing. @cherifGsoul's suggestion is a way to get around that but it'd be less confusing if the documentation could be applied directly to the default application installation, or the application template changed to match the documentation if this is the recommended way.

**Comment by samdark** [comment]
@YasserHassan it seems you're on it so it would be absolutely great to get a pull request. Do you have time for it? Thanks!

**Comment by YasserHassan** [comment]
@samdark I'd be glad to contribute. I need to make sure my understanding correct. Please verify my understanding below:
- The basic application template is the reference, the documentation will be updated to reflect it.
- The 'fixtures' and 'templates' should be stored in `@tests\codeception\unit\fixtures` and `@tests\codeception\unit\templates` respectively (or in `@tests\codeception\fixtures` and `@tests\codeception\templates`?).
- The default value of the alias `@tests` will be changed to `/tests/codeception`.

**Comment by samdark** [comment]
- Usually basic app is used as a reference, yes. Sometimes documentation uses abstract code, not the code from any template if it makes sense to do so.
- It depends on the template used. For basic it's `@tests/templates` (`tests/codeception/templates`) and `@tests/fixtures` (`tests/codeception/fixtures`). For advanced it's `@tests/codeception/common/templates/fixtures` for fixture templates and `@tests/codeception/common/fixtures/data` for fixture data.
- It's already like that for basic app i.e. `@tests` means `tests/codeception`. It is inconsistent with advanced template where `@tests` points to `tests` dir.

**Comment by YasserHassan** [comment]
@samdark to put things in perspective, the documentation currently reflects the `templates` and `fixtures` locations in a new basic app project correctly as used by the `fixture/generate` console command. My comment above was about the "suggested" locations. It would be more intuitive to use one of the two `templates`+`fixtures` folder pairs generated by the project template instead of creating new ones under a new folder `tests/unit`. For this reason I prefer your version of having the fixtures stored under the `codeception` folder (or `codeception/unit`).

However, in the basic app template, `@tests` refers to `/tests` as shown [here](https://github.com/yiisoft/yii2-app-basic/blob/master/config/console.php#L3) not `/tests/codeception`. So changing to the "suggested" or "intuitive" way would require a couple of changes around the template itself not only the documentation such as making `@tests` refer to `/tests/codeception` and its impact on `tests/codeception/config/config.php` [here](https://github.com/yiisoft/yii2-app-basic/blob/master/tests/codeception/config/config.php#L10).

I need a second opinion to validate the benefit and impact of such change to make sure it does not cause disruption. For example there are several tutorials and guides on the Web describing things they currently are.

**Comment by samdark** [comment]
It won't cause disruption.

**Comment by samdark** [comment]
For these tutorials you may send letters to their authors requesting an update.

**Comment by samdark** [comment]
Seems to be fixed.
