### ISSUE TITLE
Can we have an API template project?

### ISSUE THREAD

**Issue by lukos** [yiisoft/yii2-app-basic#184]
Currently, I believe there are only two templates: basic and advanced, but they are heavily biased towards web applications.

Since Yii2 does APIs really well, could we also have a centrally maintained API template? I have created one here: https://github.com/lukos/yii2-api-mongo that I am happy to either take PRs into to get it ready, or for you guys just to copy it as-is into yiisoft and refer to it somewhere.

Note: it is a mongodb example, I could also create a SQL one if you think it would be helpful?

**Comment by samdark** [comment]
We wanted one for Yii 3.0.

**Comment by samdark** [comment]
Feel free to play with it: https://github.com/yiisoft/app-api. And here's discussion issue: https://github.com/yiisoft/app-api/issues/1

**Comment by schmunk42** [comment]
@samdark I think yii2-app could be a CLI, API or Web project - or any mix of those. We talked about that here https://github.com/yiisoft/app/issues/2

Even for an API you need one `index.php` in public, it "usually just" returns JSON instead of HTML.
For a CLI this can be dropped, but still I don't think we need different templates.

**Comment by schmunk42** [comment]
> You could create a common template but a pure API project does not need views, assets, web/assets, web/css and also doesn't need things like the yii2-bootstrap composer package

It won't be installed, except for `views` all the other folders shouldn't exist. 

Speaking about that, I looked through the current code and I think several things should be removed, including:
- Alert Widget (use an extension or rather add a gii command which creates a widget or simply write docs about it)
- Content Page (problematic with GDPR now anyway)
- User Login (debatable, we had this discussion before; I strongly vote for an external module!)
  - since the is part of the application template you can't really update and maintain it properly

You can still argue that there's a controller and view which the API does not need necessarily, and a web-entrypoint which the CLI does not need. 

But it would be a movement in the right direction; IMO.
